server:
  port: ${SERVER_PORT}

spring :
  application:
    name: munectingV4
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          timezone: Asia/Seoul
  security:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,PATCH,DELETE
      allowed-headers: "*"
      path-pattern: "/**"

    whitelist:
      patterns: ${WHITELIST_PATTERNS}

    auth:
      header: Authorization
      prefix: Bearer

    oauth:
      kakao:
        public-key-info: https://kauth.kakao.com/.well-known/jwks.json
        issuer: https://kauth.kakao.com
        audience: ${KAKAO_APP_ID}
      apple:
        public-key-url: https://appleid.apple.com/auth/keys
        issuer: https://appleid.apple.com
        audience: ${APPLE_APP_ID}
      google:
        client-id: ${GOOGLE_CLIENT_ID}

  servlet:
    multipart:
      maxFileSize: 3MB # 파일 하나의 최대 크기
      maxRequestSize: 10MB  # 한 번에 최대 업로드 가능 용량
      resolve-lazily: true

cloud:
  aws:
    s3:
      bucket: munecting
      path:
        profile-image: profileImage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY_ID}
      secretKey: ${AWS_S3_SECRET_ACCESS_KEY}

spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

kakao-map:
  api-key: ${KAKAO_MAP_API_KEY}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:${DATASOURCE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 3600
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/munecting
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 3600
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
cloud:
  aws:
    s3:
      bucket: munecting-dev
      path:
        profile-image: profileImage
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/munecting
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

cloud:
  aws:
    s3:
      bucket: munecting-test
      path:
        profile-image: profileImage