server:
  port: ${SERVER_PORT}

spring :
  application:
    name: munectingV4
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgresSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:${DATASOURCE}://${HOST}:${PORT}/${TABLE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 3600

  data:
    redis:
      host: localhost
      port: 6379
#      password: 1234
  mail:
    debug: true
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
naver:
  id: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

spotify:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}